In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## 2.4.1 search for functions and classes

当我们**想知道一个模块里面提供了哪些可以调用的函数和类的时候**，可以使用`dir`函数。下面我们打印`dtypes`和`random`模块中所有的成员或属性。

In [2]:
dir(tf.norm)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__original_wrapped__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__wrapped__',
 '_tf_decorator',
 '_tf_dispatchers']

## 2.4.2 use of functions

想了解某个函数或者类的具体用法时，可以使用`help`函数。让我们以`ones`函数为例，查阅它的用法。更详细的信息，可以通过[Tensorflow的API文档版本选择页](https://www.tensorflow.org/versions)，选择与自己环境中的 tensorflow 版本一致的 API 版本进行查询。

In [3]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to one (1).



In [4]:
help(tf.norm)

Help on function norm_v2 in module tensorflow.python.ops.linalg_ops:

norm_v2(tensor, ord='euclidean', axis=None, keepdims=None, name=None)
    Computes the norm of vectors, matrices, and tensors.
    
    This function can compute several different vector norms (the 1-norm, the
    Euclidean or 2-norm, the inf-norm, and in general the p-norm for p > 0) and
    matrix norms (Frobenius, 1-norm, 2-norm and inf-norm).
    
    Args:
      tensor: `Tensor` of types `float32`, `float64`, `complex64`, `complex128`
      ord: Order of the norm. Supported values are `'fro'`, `'euclidean'`,
        `1`, `2`, `np.inf` and any positive real number yielding the corresponding
        p-norm. Default is `'euclidean'` which is equivalent to Frobenius norm if
        `tensor` is a matrix and equivalent to 2-norm for vectors.
        Some restrictions apply:
          a) The Frobenius norm `'fro'` is not defined for vectors,
          b) If axis is a 2-tuple (matrix norm), only `'euclidean'`, '`fro'`, 

In [5]:
tf.ones([2,6], tf.int32)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])>